#ECHO
T

#DESCRIPTION
Ideal run for southward IMF, 450km/s solar wind, no PS coupling.

#TIMEACCURATE
F			DoTimeAccurate

#STARTTIME
1998		year
05		month
04		day
00		hour
00		minute
00		second
0.0 		FracSecond

#IDEALAXES

#COUPLE2
GM			NameComp1
IE			NameComp2
10                      DnCouple
-1.0                    DtCouple

#SAVERESTART
T
5000
-1

#BEGIN_COMP GM ---------------------------------------------------------------

#GRID
1			nRootBlock_D(x_)
1			nRootBlock_D(y_)
1			nRootBlock_D(z_)
-224.			x1
 32.			x2
-128.			y1
 128.			y2
-128.			z1
 128.			z2

! Maximum resolution initially
#GRIDRESOLUTION
1.0			Resolution
initial			NameArea

! Minimum resolution in the computational domain
#GRIDRESOLUTION
8.0			Resolution
all			NameArea

! Far tail for wind satellite and inflow
#GRIDRESOLUTION
1.0			Resolution
box			NameArea
-100.0			xMinBox
 -16.0			yMinBox
 -16.0			zMinBox
  32.0			xMaxBox
  16.0			yMaxBox
  16.0			xMaxBox

! Super high at inner boundary
! to capture outflow patterns.
#GRIDRESOLUTION
1/16
box
-4.0                   xMinBox
-4.0                   yMinBox
-4.0                   zMinBox
 4.0                   xMaxBox
 4.0                   yMaxBox
 4.0                   zMaxBox

! Strong resolution just outside
! super-hi for clean outflow.
#GRIDRESOLUTION
1/8
box
-8.0                   xMinBox
-8.0                   yMinBox
-8.0                   zMinBox
 8.0                   xMaxBox
 8.0                   yMaxBox
 8.0                   zMaxBox

! Good res throughout lobes.
#GRIDRESOLUTION
1/4
box
-32.0                  xMinBox
-16.0                   yMinBox
-16.0                   zMinBox
 12.0                   xMaxBox
 16.0                   yMaxBox
 16.0                   zMaxBox

! 1/2 RE buffer around inner mag.
#GRIDRESOLUTION
1/2			Resolution
box			NameArea
-40.0			xMinBox
-24.0			yMinBox
-24.0			zMinBox
 24.0			xMaxBox
 24.0			yMaxBox
 24.0			zMaxBox

#NONCONSERVATIVE
T                       UseNonConservative

#CONSERVATIVECRITERIA
1			nConservCrit
parabola		TypeConservCrit_I
 5.0			xParabolaConserv
15.0			yParabolaConserv

#TVDRESCHANGE
T

#TIMESTEPPING
1			nStage
0.80			CflExlp

#OUTERBOUNDARY
outflow			TypeBC_I(east_)
vary			TypeBC_I(west_)
float			TypeBC_I(south_)
float			TypeBC_I(north_)
float			TypeBC_I(bot_)
float			TypeBC_I(top_)

#INNERBOUNDARY
polarwind

#SCHEME
1			nOrder
Rusanov			TypeFlux

#SAVEPLOTSAMR
F			DoSavePlotsAmr to save plots before each AMR

#AMR
100			DnRefine
F			DoAutomaticRefinement

------------------------------------------------
MULTIFLUID OPTIONS DEACTIVATED.

MULTIION
0.001                   LowDensityRatio
1e-10                   LowPressureRatio
F                       DoRestrictMultiIon

Fast, phsyics-based cutoff u_counter
COLLISION
-1.0                    CollisionCoefDim
6.0e2                   TauCutOffDim [s]
-1                      uCutOffDim [km/s] read if TauCutOffDim positive
4                       nPowerCutOff read if TauCutOffDim positive

PLASMA
1.0             FluidMass [amu]
1.0             IonCharge [e]
1.0             FluidMass [amu]
1.0             IonCharge [e]
0.2             ElectronTemperatureRatio
---------------------------------------------------

#MAGNETOSPHERE
T                       body1
2.5                     Rbody
3.0                     Rcurrents
28.00                   Magneto_rho_dim (/ccm) density for fixed BC for rho_BLK
25000.0                 Magneto_T_dim (K) temperature for fixed BC for P_BLK

[second fluid not used.]
10.0                    Magneto_rho_dim (/ccm) density for fixed BC for rho_BLK
25000.0                 Magneto_T_dim (K) temperature for fixed BC for P_BLK

#POLARBOUNDARY
0.01            PolarNDim [amu/cc] for fluid 1
25000.0         PolarTDim [K]      for fluid 1
0.0             PolarUDim [km/s]   for fluid 1
15.             PolarLatitude [deg]

Second fluid not used. For MF, change 1st fluid polar density to 28.0.
0.01            PolarNDim [amu/cc] for fluid 2
25000.0         PolarTDim [K]      for fluid 2
0.0             PolarUDim [km/s]   for fluid 2

#UPSTREAM_INPUT_FILE
T                       UseUpstreamInputFile
imf_mf_bzturn_by.dat       UpstreamFileName
0.0                     Satellite_Y_Pos
0.0                     Satellite_Z_Pos

#END_COMP GM -----------------------------------------------------------------

#BEGIN_COMP IE ---------------------------------------------------------------

#IONOSPHERE
5                       TypeConductanceModel
F                       UseFullCurrent
F			UseFakeRegion2
150.0                   F107Flux
1.0                     StarLightPedConductance
0.25                    PolarCapPedConductance

#AURORALOVAL
T			UseOval (rest of parameters read if true)
T			UseOvalShift
F			UseSubOvalConductance
T			UseAdvancedOval
F			DoFitCircle (read if UseAdvancedOval is true)

#SPS
T

#DEBUG
0
0

#END_COMP IE -----------------------------------------------------------------

#STOP
1000                     MaxIter
-1.			TimeMax

#RUN	######################################################################

#BEGIN_COMP GM ---------------------------------------------------------------

#AMR
-1			DnRefine

#SCHEME
2			nORDER
Rusanov			TypeFlux
mc3                     TypeLimiter
1.2

#TIMESTEPPING
2			nStage
0.60			CflExlp

#BORIS
T
0.02

#END_COMP GM -----------------------------------------------------------------

#STOP
5000                    MaxIter
-1.			TimeMax

#TIMEACCURATE
T			DoTimeAccurate

#SAVERESTART
T                       DoSaveRestart
-1                      DnSaveRestart
1800.0                  DtSaveRestart

#COUPLE2
GM			NameComp1
IE			NameComp2
-1                      DnCouple
5.0                     DtCouple

#BEGIN_COMP GM ---------------------------------------------------------------


#SAVELOGFILE
T			DoSaveLogfile
VAR step date		StringLogfile
-1			DnSaveLogfile
5.0			DtSaveLogfile
dt rho mx my mz p bx by bz pmin pmax dst cpcpn
3.0 3.5 5.0		StringRFlux

#SAVEPLOT
10                      nPlotFiles
y=0 MHD idl             StringPlot
-1                      DnSavePlot
60.			DtSavePlot
-1
z=0 MHD idl             StringPlot
-1                      DnSavePlot
60.			DtSavePlot
-1
3d MHD idl		StringPlot
-1                      DnSavePlot
900.			DtSavePlot
-1
y=0 ray idl             StringPlot
-1                      DnSavePlot
60.                     DtSavePlot
-1.0                    DxSavePlot
z=0 ray idl             StringPlot
-1                      DnSavePlot
60.                     DtSavePlot
-1.0                    DxSavePlot
shl MHD idl 		StringPlot
-1  			DnSavePlot
300. 			DtSavePlot
SMG 			TypeCoordPlot
6.0 			rMin
6.0 			rMax
0. 			LonMin
360. 			LonMax
2. 			dLon ! only read if LonMin /= LonMax
-90. 			LatMin
90. 			LatMax
2. 			dLat ! only read if LatMin /= LatMax
shl MHD idl 		StringPlot
-1  			DnSavePlot
300. 			DtSavePlot
SMG 			TypeCoordPlot
6.6 			rMin
6.6 			rMax
0. 			LonMin
360. 			LonMax
2. 			dLon ! only read if LonMin /= LonMax
-90. 			LatMin
90. 			LatMax
2. 			dLat ! only read if LatMin /= LatMax
shl MHD idl 		StringPlot
-1  			DnSavePlot
300. 			DtSavePlot
SMG 			TypeCoordPlot
7.0 			rMin
7.0 			rMax
0. 			LonMin
360. 			LonMax
2. 			dLon ! only read if LonMin /= LonMax
-90. 			LatMin
90. 			LatMax
2. 			dLat ! only read if LatMin /= LatMax
shl MHD idl 		StringPlot
-1  			DnSavePlot
300. 			DtSavePlot
SMG 			TypeCoordPlot
8.0 			rMin
8.0 			rMax
0. 			LonMin
360. 			LonMax
2. 			dLon ! only read if LonMin /= LonMax
-90. 			LatMin
90. 			LatMax
2. 			dLat ! only read if LatMin /= LatMax
shl MHD idl 		StringPlot
-1  			DnSavePlot
300. 			DtSavePlot
SMG 			TypeCoordPlot
10.0 			rMin
10.0 			rMax
0. 			LonMin
360. 			LonMax
2. 			dLon ! only read if LonMin /= LonMax
-90. 			LatMin
90. 			LatMax
2. 			dLat ! only read if LatMin /= LatMax

#SCHEME
2			nORDER
Rusanov			TypeFlux
mc3                     TypeLimiter
1.2			BetaLimiter

#BORIS
T
0.02

#TIMESTEPPING
2			nSTAGE
0.85			cfl

#END_COMP GM -----------------------------------------------------------------

#BEGIN_COMP IE ---------------------------------------------------------------

#SAVEPLOT
1			nPlotFile
aur idl                 StringPlot
-1                      DnSavePlot
300.0			DtSavePlot

#SPS
T

#DEBUG
0
0

#END_COMP IE -----------------------------------------------------------------

#STOP
-1			MaxIter
57600.0			TimeMax

#END
